name: scratch

ghc-options:
  - -Wall
  - -Werror

default-extensions:
  - TemplateHaskell
  - QuasiQuotes
  - OverloadedStrings
  - ViewPatterns
  - TypeFamilies

dependencies:
  - yesod-book
  - base
  - yesod
  - blaze-html
  - shakespeare
  - text
  - blaze-builder
  - http-types
  - time

executables:
  ex00:
    main: Ex00_HelloWorld.hs
  ex01:
    main: Ex01_Links.hs
  ex02:
    main: Ex02_JSON.hs
  ex03:
    main: Ex03_Shakespeare.hs
  ex04:
    main: Ex04_Widgets.hs
  ex05:
    main: Ex05_Typeclass.hs
  ex06:
    main: Ex06_Routing.hs
