name: scratch

ghc-options:
  - -Wall
  - -Werror

dependencies:
  - yesod-book
  - base
  - yesod

executables:
  ex00:
    main: Ex00_HelloWorld.hs
  ex01:
    main: Ex01_Links.hs
  ex02:
    main: Ex02_JSON.hs
