name: scratch

ghc-options:
  - -Wall
  - -Werror

dependencies:
  - yesod-book
  - base
  - yesod
  - blaze-html
  - shakespeare
  - text
  - blaze-builder
  - http-types

executables:
  ex00:
    main: Ex00_HelloWorld.hs
  ex01:
    main: Ex01_Links.hs
  ex02:
    main: Ex02_JSON.hs
  ex03:
    main: Ex03_Shakespeare.hs
